### ISSUE TITLE
suddenly today my controlnet causes my sd webui to freeze after restarting my pc

### ISSUE THREAD

**Issue by MalfreCryvertia** [Mikubill/sd-webui-controlnet#1220]
it is just as usual;
1. enable controlnet, 
2. put image in, 
3. choose preprocessor
4. choose model
5. generate
6. usually it starts then voila but nope, it does start but immediately stops after 2 seconds, then generate button becomes unfunctional
if i try generate again, my webui actually freezes and i cannot do anything except restarting

today it suddenly becomes like this even though i changed nothing, no install, no uninstall, no updates on my computer

tried deleting controlnet, restart webui, install controlnet again, put my models in, restart webui, but nope, issue still persists
looked for this kind of issue on github and google search but nothing was similar
"sd webui / a1111 / controlnet + freeze / generate button not working"

would love some help as i use controlnet everyday A LOT haha

**Comment by TerrinX** [comment]
me too

**Comment by lllyasviel** [comment]
what

**Comment by MalfreCryvertia** [comment]
> what

exactly what i described, i went to work so i turned off my pc, then when im back, turned it on, suddenly it becomes like this

**Comment by huchenlei** [comment]
Here are some approaches you can try:

- Trying to narrow down the cause. Do a fresh WebUI checkout, does it work? Only install controlnet extension (latest version), does it work?
- Roll back to an older version of controlnet (You can do this by getting older version hashes through `git log --oneline`, and `git checkout {version hash}` to load specific version within `extensions/sd-webui-controlnet` directory.
- Attach the console log so that we can have more context.
- Sometimes WebUI freezes in the commandline. You just to need press `Enter` to unblock it.
