### ISSUE TITLE
[Bug]: Batch mode not compatible with any dynamic prompt extensions (Workaround included)

### ISSUE THREAD

**Issue by atabatic** [Mikubill/sd-webui-controlnet#1393]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hello, when ControlNet is in Batch mode and given a directory of poses, any extensions (Dynamic Prompts, ADetail) designed to randomize the image prompt do not trigger and only occur once for the set number of images, instead of the number of poses.

version: [v1.2.1]  •  python: 3.10.11  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint: [4caa3946ca]

### Steps to reproduce the problem

- When ControlNet **IS NOT** enabled, the prompts randomize as expected and proceed through the poses folder as expected.
- When ControlNet **IS** enabled in batch mode, the prompts do not randomize as expected.
- When ControlNet **IS** enabled in batch mode and "Batch count" is set to 100, the first # properly cycle prompts. However, if there are more than 100 poses, these prompts cycle.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/68980874/23678dc1-267a-489d-9ea6-efbf88188ed8)
- When ControlNet **IS** enabled in batch mode and "Batch size" is set to 100, the first # properly cycle prompts. However, if there are more than 100 poses, these prompts cycle.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/68980874/a3c8de57-6da9-48cf-976b-d6f1935e8edf)
- When ControlNet **IS** enabled in batch mode and "Batch count" is set to 2, the first # properly cycle prompts. However, if there are more than 2 poses, these prompts cycle.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/68980874/a80d0a58-88e4-4c78-addd-8b1a25410002)

### What should have happened?

ControlNet in batch mode should be triggering a prompt refresh and cycle through other extensions that randomize the prompt.

### Commit where the problem happens

version: [v1.2.1]  •  python: 3.10.11  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint: [4caa3946ca]

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--opt-sdp-attention --autolaunch --api --ckpt-dir "X:\stable-diffusion-webui\models\Stable-diffusion"
```

### List of enabled extensions

- ADetailer (tried with and without)

### Console logs

```Shell
Will modify and attach here after my current batch run completes
```

**Comment by ljleb** [comment]
Part of the problem seems to be that controlnet batch uses an outer batch loop, calling process as many times as needed, instead of using the generation batch count. Another way to look at it, is that the other extensions use the generation batch loop, instead of using an outer batch loop, to generate images.

The reason controlnet uses the outer batch count is to stay consistent with how the webui's img2img batch tab works. If you go to the img2img batch and launch controlnet, it will fallback to using the webui's batch behavior, which should give you the same erroneous behavior.

The only solution to this, to the best of my knowledge, is to create a proper batch api in the webui so that extensions can communicate.

For the randomization, it's because batch does not make a copy of `p`, and dynamic prompts modifies `p` in place, making the prompt static for the rest of the generations.

**Comment by atabatic** [comment]
Update: I installed some more extensions and changed some settings and this problem appears to have another workaround, I'm trying to isolate it.

**Comment by DEC1MU5** [comment]
> Update: I installed some more extensions and changed some settings and this problem appears to have another workaround, I'm trying to isolate it.

This is a fairly recent thread, something I hope will be fixed in a future update.
Would you mind sharing some input about how you fixed/workaround this issue?
I am experiencing the same issue you describe and I would also like to generate a large batch of poses that aren't boring and properly use my dynamic prompting. Any help is appreciated.

**Comment by charliemagee** [comment]
I'm having a similar, but different issue. Batch mode isn't "hanging tight" to my settings. The images are close, but colors drift all over the place, making my animations look stinko. But if I run my images one at a time, then everything is locked in and my animation looks good. This is a major problem for me. I've got thousands of images to run.

I'm on a Mac, so I'm wondering if that's part of my issue.

**Comment by mrjw717** [comment]
I had the same issue last night and walked away from it determined to figure it out today. I'm running google Colab on their GPU and having the same issue. 

@atabatic 
> Update: I installed some more extensions and changed some settings and this problem appears to have another workaround, I'm trying to isolate it.

-            Would you mind sharing what your thought process is or what may be working for you? Desperate to find a solution.

**Comment by DEC1MU5** [comment]
I seem to have better (not perfect) results, if I just generate batches of 400 rather than "generate forever"
I think there may be a way to modify that default settings as well, so you could make larger batches.

**Comment by Elevenheights** [comment]
Has anyone figured out a workaround to this yet?

**Comment by DEC1MU5** [comment]
I've had some luck running extremeley large Prompts with BREAK points after each area.
Like Figure
BREAK
Hairstyles 
BREAK
Clothing
 BREAK
Photo Style
BREAK
Location
BREAK

This is a great way to avoid the too many tokens error and seems to help High Res AS well.

Another thing I've been doing is by doing High Res Outputs WITHOUT Resizer and using a lycoris Plug called "HD_Helper"
I can still get great results (mostly) on large batches using this.
