### ISSUE TITLE
[Feature]: Uni-Controlnet

### ISSUE THREAD

**Issue by 2blackbar** [Mikubill/sd-webui-controlnet#1429]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

You guys plan to support this one ?
https://github.com/ShihaoZhaoZSH/Uni-ControlNet
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/33694664/09a1a753-f5e0-4d2f-8ba9-92bec8ef30b1)

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

.

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
.
```

### List of enabled extensions

.

### Console logs

```Shell
.
```

**Comment by ghpkishore** [comment]
@2blackbar  Isnt this same as whats possible with multi controlnet?  Can you explain more on how this would be different from using multi controlnet to get your results?

**Comment by lllyasviel** [comment]
Many new methods are proposed recently because of the neurips deadline. 

To avoid bias and excessive workload, we will implement more methods after the neurips decision, unless any extremely important methods are proposed (e.g., if very strong evidences show that users can always get significantly better results from other codebase than the current toolset in CN, or if users can achieve significantly more efficient new ways of editing with other codebase).

**Comment by 2blackbar** [comment]
This is another one  https://github.com/salesforce/UniControl
I think they just use one model  for all the tasks as it understands them all ? Their results are kinda good with some tasks , thats pretty cool, saves space and can do a lot

UniControl is a unified model (1.4B #params, 5.78GB checkpoint) capable of handling various visual conditions for the controllable visual generation.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/33694664/6a4f9021-5277-4fec-8ad7-f43ef0e2ebdb)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/33694664/7ed1717b-a2c5-4c26-be78-7204892a5a18)
