### ISSUE TITLE
Does CN pick input file randomly in batch mode?

### ISSUE THREAD

**Issue by andyvha** [Mikubill/sd-webui-controlnet#1592]
I use CN v1.1.219 on A1111 v1.3.2, I use batch mode for openpose and input folder of image. When I watch the ouput folder, I see CN pick input files not follow alphabet name or size or date..., look like it picks random file from input folder to generate image. 

Anyone can suggest me how to force CN pick file sorted by name from A to Z. I want to do this for other modes like depth, canny... as well. I can edit the python code. Thanks in advance!

**Comment by ljleb** [comment]
controlnet uses file system order at the moment, which is OS dependent. This is because the webui also uses this order when generating in the builtin img2img batch tab. We want to keep the same order as the webui.

To sort these files, have a look at this function:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/baf6946e06249c5af9851c60171692c44ef633e0/modules/shared.py#L808-L810

All you should need to do is sort the output before returning it, i.e. using `sorted` or `list.sort`

**Comment by ianvalox** [comment]
> controlnet uses file system order at the moment, which is OS dependent. This is because the webui also uses this order when generating in the builtin img2img batch tab. We want to keep the same order as the webui.
> 
> To sort these files, have a look at this function: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/baf6946e06249c5af9851c60171692c44ef633e0/modules/shared.py#L808-L810
> 
> All you should need to do is sort the output before returning it, i.e. using `sorted` or `list.sort`

Thanks for the answer. This helped me understand the problem I've been encountering. 

When using ControlNet in combination with Ultimate SD Upscale in batch mode the results are bugged. Some images get weird ghosting. I've been trying to figure out how to solve this issue with no success. It happens on my pc (Windows 10) and on web gpu (Linux). 

After reading your answer I came to a conclusion that it is propably because of different file order between controlnet and webui.   It only occurs when using batch mode. Here is an image about the problem: 
![00355-3950586097](https://github.com/Mikubill/sd-webui-controlnet/assets/137178492/b71d5265-6136-4ed5-b673-cd91c6916b5b)

I will do some additional testing later (renaming files to most simply form, etc).
