### ISSUE TITLE
[Bug]: ControlNet don't work at all

### ISSUE THREAD

**Issue by ArsenVasRa13** [Mikubill/sd-webui-controlnet#1594]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Its just not working and the command prompt give me next reason: Error running process: E:\StableDifussionE\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet .py

### Steps to reproduce the problem

1. Download
2. Generate image with CN
3. Error

### What should have happened?

It was supposed to create a picture with the same pose as in the given photo

### Commit where the problem happens

webui: idk bruh, latest i guess
controlnet: 1.1.220

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --autolaunch --precision full --no-half --skip-torch-cuda-test --force-enable-xformers
```

### List of enabled extensions

canvas-zoom, deforum, posex, sd-webui-controlnet, sd-webui-depth-lib, LDSR, LORA, ScuNET, SwinIR, prompt-bracket-checker

### Console logs

```Shell
https://pastebin.com/4BcRK92m
```

**Comment by lllyasviel** [comment]
Hello, please try the below steps and see if problems are solved:

1. update A1111 and CN to latest version. Make sure to restart terminal after update.
2. disable all other A1111 extensions.
3. disable all browser extensions or change another browser.
4. remove all cmd flags in A1111.
5. delete "config.json" and "ui-config.json". (dangerous, remember to backup files)
6. make sure that you have followed the official instruction to download ControlNet models, and make sure that each model is about 1.4 GB large.
7. uninstall ControlNet by removing the controlnet folder and try to install again.
8. make sure to not quit your webui when ControlNet is downloading preprocessor in the background terminal.
9. try to add “--no-gradio-queue” to your a1111 cmd flags.

The above steps can solve 99% problems. After your problem is solved, you can begin to enable other extensions one-by-one or add A1111 cmd flags one-by-one to find out what is causing problems and let us know.

If you are the unlucky 1%, you can try to use "git checkout" to find out if previous versions of CN works for you, and if that is the case, please let us know your last working version so that we can debug the problem.

If you still cannot solve the problem, please give as detailed as possible info about your environment.

**Comment by lllyasviel** [comment]
and https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11063

**Comment by ArsenVasRa13** [comment]
I'm going to cry because I don't know what I can do

**Comment by lllyasviel** [comment]
Closed as no further info is given.
However, the log looks like GPU driver problem. Consider downgrading to driver version 531.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11063

**Comment by ArsenVasRa13** [comment]
Hello! I do not know what I can add to my information about the problem because I am a beginner. Maybe you can tell me what I should tell?

**Comment by xavierseb** [comment]
found a solution, store the image file directly in the stable-diffusion-webui directory, and when specifying the file name, omit the entire path, specify just the filename, e.g. test.png

it seems to have issues with file paths.
