### ISSUE TITLE
(ERROR) [.] Could not set ControlNet value: invalid literal for int() with base 10: 'initial'

### ISSUE THREAD

**Issue by SteveM50** [Mikubill/sd-webui-controlnet#1617]
sice update to 1.1.219

(ERROR) [.] Could not set ControlNet value: invalid literal for int() with base 10: 'initial'

control mode and resize mode is not clickable

**Comment by lllyasviel** [comment]
Hello, please try the below steps and see if problems are solved:

1. update A1111 and CN to latest version. Make sure to restart terminal after update.
2. disable all other A1111 extensions.
3. disable all browser extensions or change another browser.
4. remove all cmd flags in A1111.
5. delete "config.json" and "ui-config.json". (dangerous, remember to backup files)
6. make sure that you have followed the official instruction to download ControlNet models, and make sure that each model is about 1.4 GB large.
7. uninstall ControlNet by removing the controlnet folder and try to install again.
8. make sure to not quit your webui when ControlNet is downloading preprocessor in the background terminal.
9. try to add “--no-gradio-queue” to your a1111 cmd flags.

The above steps can solve most problems. After your problem is solved, you can begin to enable other extensions one-by-one or add A1111 cmd flags one-by-one to find out what is causing problems and let us know.

You may also try to use "git checkout" to find out if previous versions of CN works for you, and if that is the case, please let us know your last working version so that we can debug the problem.

If you still cannot solve the problem, please give as detailed as possible info about your environment.

**Comment by Dekubaka** [comment]
I get this error as well but it doesn't seem to stop anything.

**Comment by huchenlei** [comment]
Lack of context. Please reopen a new issue with more reproduction steps if the issue is still there.
