### ISSUE TITLE
ControlNet keeps running even after Memory Error

### ISSUE THREAD

**Issue by Morgens7ern** [Mikubill/sd-webui-controlnet#1628]
Almost half the times i try using ControlNet, i get an Memory error. When it happens, i can't do anything cause it keeps running on the background consuming Vram, and i have to reopen SD.
I don't know how to fix it, i know nothing about coding and python.

![msedge_nKKiqyxJRt](https://github.com/Mikubill/sd-webui-controlnet/assets/79327382/fc45dc06-d0e2-40c4-9419-2aab164435b7)

My GPU is a GTX 1660 super 6GB
I use --xformers --medvram --no-half
Low Vram checkbox enabled

Sorry for any mistake, english is not my first language.

**Comment by eniora** [comment]
Had the same, fixed it by enabling "**sdp - scaled dot product**" in **Settings > Optimizations**
Make sure to click **Apply settings** on top after setting it. This not only fixes this issue, but allows you to generate much higher resolutions in txt2img, etc.

**Comment by andreszs** [comment]
Same card and same problem here with **Controlnet v1.1.233**, only the **first** image is generated and the next one fails with CUDA out of memory error. I'm running webuid with [these settings](https://www.andreszsogon.com/fix-stable-difussion-automatic1111-webui-on-geforce-gtx-16xx/)

> Had the same, fixed it by enabling "**sdp - scaled dot product**" in **Settings > Optimizations** (...) You also don't need the --medvram ARG for this optimization option.

What video card do you have? Those settings didn't fix the problem, and removing **--medvram** causes non-controlnet images to run out of memory as well.

@Morgens7ern did you find a solution for this card?  Note that using latest Nvidia driver, --medvram is no longer required but images are 4x slower to generate, so I reverted to driver **v531** which is faster but requires --medvram and keeps failing with Controlnet+Openpose. I won't use the latest driver again because it takes almost 2 minutes to generate a 512x512 image, while v531 does it in 16 seconds with this card.

Having to restart SD webui because controlnet does not know how to clear RAM/VRAM is far from ideal. I'm sure it works fine on cards with 24GB VRAM, but **clearing used memory shouldn't be an impossible mission**.
