### ISSUE TITLE
[Feature Request] Postprocess scripts

### ISSUE THREAD

**Issue by olamedia** [Mikubill/sd-webui-controlnet#1674]
What problem the feature is trying to solve:
Postprocess generated maps. For example, script that loads openpose json, and trying to fix pose using various models.

Expected workflow for user:
1. select script from selectbox, similar to scripts at the bottom of the txt2img and img2img pages

Expected workflow for script:

0. maps are generated
1. receive list of generated maps
2. postprocess them
3. output list of processed maps

**Comment by huchenlei** [comment]
For openpose, if you have a script that can improve detection accuracy, I would suggest directly add that to ControlNet's openpose detection preprocessor, instead of doing a post process script. 

Also, for now if you really want to correct the inaccurate detections in openpose, we have the integrated openpose editor to do that job: https://github.com/huchenlei/sd-webui-openpose-editor

**Comment by olamedia** [comment]
It's to modify already generated maps. For openpose it should be possible to calculate and fix impossible angles and proportions automatically.

I like this editor, but script would be able to perform this in batch.

**Comment by olamedia** [comment]
An example of postprocessing for openpose can be opensim which can "constraining angles to a biomechanically accurate model" - a conversion to the opensim is already exists as https://github.com/perfanalytics/pose2sim#with-openpose

**Comment by olamedia** [comment]
Here is another example of correction script https://github.com/DGS-Korpus/Public-Corpus-OpenPose-error-corrector
