### ISSUE TITLE
Refresh model button is broken

### ISSUE THREAD

**Issue by CCRcmcpe** [Mikubill/sd-webui-controlnet#18]
To reproduce, put a new model into models directory.

**Comment by synchysis** [comment]
After a fresh install of automatic1111 WebUI and this repo, I had the same problem. I was able to get my button working by hardcoding the model directory location on line 21 of controlnet.py like so:

`cn_models_dir = "L:/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/models"`

So it appears that the problem is with the bit that sets the model directory, not the rest.

**Comment by TWIISTED-STUDIOS** [comment]
even after setting the model directory, I have nothing that shows up anywhere either.

**Comment by Mikubill** [comment]
Restart WebUI will always force reload all models. I still looking for some solution to handle updates with gradio.

**Comment by TWIISTED-STUDIOS** [comment]
> Restart WebUI will always force reload all models. I still looking for some solution to handle updates with gradio.

I have tried this, I have force reloaded the UI I have changed the directory and nothing shows up anywhere, im not sure if its because my default models location folder is not inside the SD Webui directory even when tried in the Extention Models location and the Default location nothing works, Im using this install that allows you to change directory locations etc, but im not sure if this breaks something with your extension, <https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/releases>

**Comment by Mikubill** [comment]
> changed the directory and nothing shows up anywhere, im not sure if its because my default models location folder is not inside the…

You should put your models in `<extension-folder>/sd-webui-controlnet/models` or it will find nothing since custom model path is not supported yet. If the problem persists, upload your log and create a new issue.

**Comment by TWIISTED-STUDIOS** [comment]
> > changed the directory and nothing shows up anywhere, im not sure if its because my default models location folder is not inside the…
> 
> You should put your ControlNet models in `<extension-folder>/sd-webui-controlnet/models` or it will find nothing since the custom model path is not supported yet. If the problem persists, upload your log and create a new issue.

that has been done I tried this they are in the extensions model file and I do not see them in any list to choose from I have even made the change above with the .py file.

**Comment by SanDiegoDude** [comment]
> After a fresh install of automatic1111 WebUI and this repo, I had the same problem. I was able to get my button working by hardcoding the model directory location on line 21 of controlnet.py like so:
> 
> `cn_models_dir = "L:/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/models"`
> 
> So it appears that the problem is with the bit that sets the model directory, not the rest.

Even this didn't work for me. guess I'll just wait for a fix, can't seem to get models to populate. I put them in the right spot, tried refreshing UI, tried restarting A1111 completely, still no dice. Just doesn't see them.

**Comment by Mikubill** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/230a632ef52a5a2e1265f20396f41509ef65e8b0, now it should work.

**Comment by CCRcmcpe** [comment]
Confirmed working

**Comment by MNeMoNiCuZ** [comment]
It may be different, but I'm seemingly having this issue right now.
