### ISSUE TITLE
I'm using adetailer which uses controlnet inpaint. Updated to latest version of controlnet and the inpaint is bugged

### ISSUE THREAD

**Issue by dilectiogames** [Mikubill/sd-webui-controlnet#1802]
sorry. so the issue is described here with examples. I don't know which has the bug but same adetailer version with a previous controlnet version worked fine

https://github.com/Bing-su/adetailer/issues/216

**Comment by huchenlei** [comment]
Not reproducable in my local setup. You can do a bisect between the version you upgraded from and the current version. If you can identify a culprit commit, we can see whether we can fix or revert it. Please re-open after you have identified culprit.

**Comment by huchenlei** [comment]
Note: the core python code has not been updated for about a month. All recent changes are either front-end only, API change and documentation.

**Comment by dilectiogames** [comment]
I've did some tests the version on controlnet v1.1.231 1770 dd766de8629ee6035a734217e08c26cd1b08b2ab) is the one that works perfectly and both v1.1.232 and v1.1.233 do not work. (I've tested the last commit of each version)

here is an image that shows the issue there are no artefacts in the hair, the eyelashes look more defined, the colors match the rest of the image, the body. this for the version v1.1.231

![example](https://github.com/Mikubill/sd-webui-controlnet/assets/126326386/c62be540-69c8-4df7-b63f-3442458d3e36)

if you want to replicate this you need

adetailer v23.6.3 and sd-webui-lora-block-weight 8ba434ef1e90217b8cd7c877e42980d3d1b4f9d6 all to last version as for today. I've only reverted controlnet to the previopus versions like in the image

you can get the prompts and the loras I've used form civitai from the the two links bellow. Save image as jpg and load in the png info to get the full prompt for adetailer. loras are on the right

https://civitai.com/images/1611646?period=AllTime&periodMode=published&sort=Newest&view=feed&username=dilectiogames&withTags=true

https://civitai.com/images/1601542?period=AllTime&periodMode=published&sort=Newest&view=feed&username=dilectiogames&withTags=true

thank you for your help and for the great work done on this extension hope this issue gets resolved. :D

**Comment by dilectiogames** [comment]
I don't know how to reopen so hope you see the message above :)

**Comment by huchenlei** [comment]
1.1.232 removes dynamic reloads of modules #1775, as in A1111 1.4.0 the extension reloading behaviour has been changed. Can you try to completely restart WebUI from commandline and see if the issue persists?

**Comment by dilectiogames** [comment]
when doing the the tests above I've closed automatic command line window, before changing the commit. Is this what you mean by restarting the webui? I've noticed this issue for the past few days so it persist over restarting the computer so I don't know :|

I'v4e forgot to add but automatic is on the latest version

Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8

**Comment by huchenlei** [comment]
Add @ljleb to discussion, as I cannot really think of any problem can be caused by removing those reloads.

**Comment by marcsyp** [comment]
I can confirm that I am also having problems with the latest version when using SD Ultimate Upscale -- images are completely forked, looks like the tiles are misregistered, causing ghosting and tile edge mismatch.  I suspect this is caused by the same root cause as @dilectiogames problem with ADetailer, and is related to tile/inpaint scaling issues.  However, in case it is different, I will post a new issue in a bit with some samples and reference it here.  Thx.

**Comment by huchenlei** [comment]
> I can confirm that I am also having problems with the latest version when using SD Ultimate Upscale -- images are completely forked, looks like the tiles are misregistered, causing ghosting and tile edge mismatch. Rolling back fixes the issue. I suspect this is caused by the same root cause as @dilectiogames problem with ADetailer, and is related to tile/inpaint scaling issues. However, in case it is different, I will post a new issue in a bit with some samples and reference it here. Thx.

Do you also found the culprit to be between version 1.1.231 and 1.1.232?

**Comment by marcsyp** [comment]
I will test which version breaks it for me and post an issue tomorrow. Thx

**Comment by marcsyp** [comment]
hmmmm..... so, i guess never mind.  I can't seem to reproduce the issue I was having.  I was working with a lot of loras and a mixture of syntax errors that was creating some loras to remain in memory, and I think restarting the server was the thing that fixed my issue (not the rollback that I also did at the same time).  I'll keep an eye on it if it comes up again.

**Comment by huchenlei** [comment]
I will take a closer look if more people are reporting the same issue, as I cannot reproduce the issue on my local setup.

**Comment by tip0un3** [comment]
Ah, I'm not the only one. I use adetailer a lot. I noticed a problem with Tile since version v1.1.232, so I stayed with version v1.1.231.
I've created an example for comparison. I use it for example to modify a background and an outfit. I use adetailer for an auto mask on the face and then reverse the mask with a Tile treatment. This makes it easy to change clothes and background without changing the face.

That's the kind of result I get :
![0](https://github.com/Mikubill/sd-webui-controlnet/assets/84997477/e5957e5f-583e-4213-a35f-a267590791fa)
Original image

![1](https://github.com/Mikubill/sd-webui-controlnet/assets/84997477/9f5abd47-51e0-496a-b755-af6aa3f23cf5)
Tile ControlNet v1.1.231 adetailer (resultat good)

![2](https://github.com/Mikubill/sd-webui-controlnet/assets/84997477/5d235280-66a5-4a32-aa7c-eac16228e9f2)
Tile ControlNet v1.1.232 adetailer (the result is not good on clothes)

The difference is truly striking, yet the settings are exactly the same. I don't know what it's due to.
The behavior of the 2 versions on the various ControlNet seems to be quite different...

**Comment by DemitriLatet** [comment]
Same here, ADetailer is not working in recent versions of controlnet.

**Comment by 2blackbar** [comment]
that a big deal, adetailer is a must to get good face on images

**Comment by marcsyp** [comment]
@huchenlei @dilectiogames @lllyasviel 

UPDATE:

I have discovered the source of my upscaling issues (using Ultimate Upscale), and it does not have to do with ADetailer or ControlNet versions.  It has two components:

1) Minor: Installing "Composable Lora" degrades the upscaling results (even when Composable Lora is disabled)
2) Major: Updating to Torch 2.0 and xformers 0.2.  I rolled back everything way back in time to the last known configuration to work, slowly and progressively, disabling extensions, rolling back CN versions, etc, etc, etc.  First I discovered point 1) above.  But all my upscaling issues were rectified as soon as I went back to:

torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.23.0  •  commit: [a5c12b81](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a5c12b81288146963a99afcc481989954964c436)  •  CN 1.1.216

Even using these A1111 + CN commits with torch 2.0 setup resulted in significantly degraded upscaling.  

Any thoughts on where I should log a new issue?  I believe that the root cause that is affecting Ultimate Upscale may also be affecting other plugins, so it may be of benefit to the entire ecosystem to solve this.  I suspect that A1111-webui is the right repo to log the issue, but would love feedback.  For now I am stuck on a very old A1111 + CN until I can resolve this, because high quality massive upscaling is an absolutely critical part of my artistic process.  

Thanks,
Marc

**Comment by huchenlei** [comment]
@marcsyp Thanks for the update! I think you should definitely file an issue in A1111 repo. Does this issue happen for all upscaling tasks or only for upscaling of large images?

**Comment by marcsyp** [comment]
So far the differences are obvious in very large upscales (3x, 13000x19000), and I _believe_ that I have observed differences in smaller upscales (512x766 to 1536x2328), but I will need to do some more testing on smaller upscaling to answer that question more confidently.  I'll do that hopefully tonight since I'm leaving town for 9 days or so tomorrow and won't have access to my home machine.  Cheers.

**Comment by marcsyp** [comment]
@huchenlei 

I have confirmed that the issues are also definitely present in smaller upscales, they are just not as noticeable because there are generally fewer fine details to compare before and after, compared to large upscales.  But it appears that there is some kind of shifting/image position registration problem happening in the model, causing a ghosting effect that is partially removed by the denoising that happens in the img2img process, but generally degrades the image quality, particularly on detailed areas.  It also adds detail to certain areas of the image because there are "double textures" in parts that the denoising then renders into a dense texture.  I will find a denoising strength and set of images that best illustrate the issues and post on A1111.  Thanks.

**Comment by marcsyp** [comment]
An interesting side note, however: ControlNet Is More Important does not seem to have the same issue, it only is a problem with Balanced mode in ControlNet.  Food for thought.
