### ISSUE TITLE
[Bug]: Empty Image Returned: API controlnet/detect

### ISSUE THREAD

**Issue by Tsukihara0w0** [Mikubill/sd-webui-controlnet#1830]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When sending images to the `/controlnet/detect` endpoint, the returned response contains an empty image data: `{"images":[""],"info":"Success"}`.

### Steps to reproduce the problem

```
import cv2
import base64
import requests


# A1111 URL
url = "http://127.0.0.1:7860"

# Read Image in RGB order
img = cv2.imread('img.png')

# Encode into PNG and send to ControlNet
retval, bytes = cv2.imencode('.png', img)
encoded_image = base64.b64encode(bytes).decode('utf-8')

# detect payload
payload = {
    "controlnet_module": "invert",
    "controlnet_input_images": [encoded_image],
    "controlnet_processor_res": 512,
}

# Trigger Generation
response = requests.post(url=f'{url}/controlnet/detect', json=payload)

print(response.text)
```
response
```{"images":[""],"info":"Success"}```

### What should have happened?

This seems to be due to the encode_to_base64 function. 
The encode_to_base64 function is returning an empty string. 
However, I'm not a programmer, so I'm not sure if this is correct.

### Commit where the problem happens

webui: v1.4.1
controlnet: v1.1.233

### Command Line Arguments

```Shell
--api
```

### List of enabled extensions

only contorlnet

### Console logs

```Shell
2023-07-25 19:18:38,996 - ControlNet - INFO - Detecting 1 images with the invert module.
```

**Comment by tykji93** [comment]
I have a same issue

**Comment by yoebet** [comment]
Same issue. I am using the `invert` preprocessor.
After some inspecting, I spot here https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/api.py#L21 

```python
def encode_to_base64(image):
    if type(image) is str:
        return image
    elif type(image) is Image.Image:
        return api.encode_pil_to_base64(image)
    elif type(image) is np.ndarray:
        return encode_np_to_base64(image)
    else:
        return ""
```

I found that in order to cache the fun call, the detect api wrapped np.ndarray to HashableNpArray. In the case of `invert`, the incoming arg is HashableNpArray(after wrapping), its return also HashableNpArray. So the above code `type(image) is np.ndarray` failed to match, returning "". 
Maybe the code `type(image) is np.ndarray` could be change to `isinstance(image, np.ndarray)`
