### ISSUE TITLE
[Bug]: Gradio3.39，Display error issues，GradioDeprecationWarning

### ISSUE THREAD

**Issue by wzgrx** [Mikubill/sd-webui-controlnet#1879]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Gradio3.39，Display error issues，GradioDeprecationWarning

### Steps to reproduce the problem

 with gr.Tab("Generation", id="txt2img_generation") as txt2img_generation_tab, gr.Row().style(equal_height=False):
G:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:165: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row(elem_classes=["cnet-image-row"]).style(equal_height=True):
G:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:179: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.generated_image = gr.Image(
G:\stable-diffusion-webui\modules\ui.py:646: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Tab("Generation"

### What should have happened?

 with gr.Tab("Generation", id="txt2img_generation") as txt2img_generation_tab, gr.Row().style(equal_height=False):
G:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:165: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row(elem_classes=["cnet-image-row"]).style(equal_height=True):
G:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:179: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.generated_image = gr.Image(
G:\stable-diffusion-webui\modules\ui.py:646: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Tab("Generation"

### Commit where the problem happens

webui: sdxl dev
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

no

### Console logs

```Shell
with gr.Tab("Generation", id="txt2img_generation") as txt2img_generation_tab, gr.Row().style(equal_height=False):
G:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:165: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row(elem_classes=["cnet-image-row"]).style(equal_height=True):
G:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:179: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.generated_image = gr.Image(
G:\stable-diffusion-webui\modules\ui.py:646: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Tab("Generation"
```

**Comment by huchenlei** [comment]
Discord discussion snippet with AUTO and other WebUI devs:

w-e-w — Yesterday at 11:14 AM
@HCL since your hear, a heads up
we swich to gradio 3.39 in dev
and some stuff in controlnet 
B:\GitHub\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:165: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row(elem_classes=["cnet-image-row"]).style(equal_height=True):
B:\GitHub\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:179: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.generated_image = gr.Image(
 
AUTOMATIC — Yesterday at 11:14 AM
there is a new setting to ignore those
i think extensions don't need to fix this soon
since they want to work on different versions
w-e-w — Yesterday at 11:15 AM
I agree it's just a heads up
and it's only a deprecation warning
as opposed to deprecated
HCL — Yesterday at 11:18 AM
Thanks! it is good to know that. Do we have a guideline on when to stop supporting a legacy version of WebUI?
w-e-w — Yesterday at 11:18 AM
not really
I do plan to implement something so that we can pair webui and extension version 
 
I bet when 3.39 is pushed to master
some users are going to open issue posts thinking that deprecation warning is a bug
deprecation warning is a feature
KBlueLeaf@LyCORIS — Yesterday at 11:23 AM
:AZUR:
w-e-w — Yesterday at 11:25 AM
well it is
you can either deprecate something immediately
or  you can set certain things as deprecated and print warnings to warn users and doing this time support both
and after the transition period has passed you stop supporting it
it is a feature that needs extra implementation
