### ISSUE TITLE
[support] controlnet-sdxl 

### ISSUE THREAD

**Issue by uk9921** [Mikubill/sd-webui-controlnet#1906]
Hi, everyone, about ten hours ago, diffusers supported [controlnet-canny-sdx](https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0)l. It looks pretty good. Do you have any plans to follow up with webui-controlnet?

**Comment by huchenlei** [comment]
No for now, since A1111 has no good support for diffusers. SDNext has good support for diffusers pipeline and should have the native support of ControlNet soon. https://github.com/vladmandic/automatic

I confirmed with Vlad that they probably will build ControlNet as first party feature, instead of extension and they will likely not building upon this repo's code.

Do note that that ControlNet model is an "old style" one which is 5GB in size. This puts the model out of reach to most users' hardware.

**Comment by huchenlei** [comment]
You can join SDNext's discord server to track the progress or just open an issue/discussion there.
