### ISSUE TITLE
[Bug]: MLSD works in the ui version but does not through api

### ISSUE THREAD

**Issue by HG2407** [Mikubill/sd-webui-controlnet#2360]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

OS: Ubuntu
browser: none

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

the mlsd image should have been respected and the output image should have followed the structure of the input image.

### Commit where the problem happens

webui: [commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)
controlnet: [commit](https://github.com/Mikubill/sd-webui-controlnet/pull/2325)

### What browsers do you use to access the UI ?

Google Chrome, Brave

### Command Line Arguments

```Shell
--share --listen --api
```

### List of enabled extensions

just the controlnet extension

### Console logs

```Shell
-
```

### Additional information

I tried changing the threshold_a and threshold_b value to 0 but nothing happened and the output didn't follow the original image's structure

**Comment by huchenlei** [comment]
Input image:
![244550333-cf7f82aa-78ee-4876-acc1-de6c6be76663](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/1cda83d9-4e5c-4269-b46e-7e3c38f650af)

MLSD infered from /detect endpoint:
![download (1)](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/da78eb38-64b2-4d90-be20-37e5bb84312e)

SD output with /txt2img endpoint:
![244550333-cf7f82aa-78ee-4876-acc1-de6c6be76663](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/020587f7-149b-43c7-8f8c-ba219ba8613d)

I do not think there is a problem with MLSD in API. Please open a new issue with console output and reproduction steps so that we can know more about your case.
