### ISSUE TITLE
[Feature Request] More hires fix options

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#2378]
Original discussion: #1826.

We should provide option per ControlNet unit to let user pick how the ControlNet unit should apply:
- To both pass
- Only low res pass
- Only high res pass

**Comment by huchenlei** [comment]
![1704083434272](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/d78fc93d-7fe0-4e17-959f-5db6616ca527)

The radio group only appears when hires fix is selected in A1111.

**Comment by AugmentedRealityCat** [comment]
I was getting errors and could not use ControlNet before I managed to discover and assign a value to this new setting. 

Maybe there is a way to give that new "Hires-Fix Option" paramater a default value to prevent this problem ?

Thanks for the new option by the way !

**Comment by CurtisDS** [comment]
when you choose "low res only" or "high res only" it still generates preview files for both

**Comment by CurtisDS** [comment]
> The radio group only appears when hires fix is selected in A1111.

@huchenlei can this be changed to always show? Now that A1111 has the "upscale" button I would like to be able to change this setting while the hires fix checkbox is off so that my choice still gets applied when I hit the upscale button.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20732674/fae7271f-9385-4a6b-afc6-a49e2b94373a)
