### ISSUE TITLE
[Bug]: Ending Control Step not working after first generation

### ISSUE THREAD

**Issue by hellomrmarky** [Mikubill/sd-webui-controlnet#2752]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Seems like after the recent update the setting for "Ending Control Step" is broken after first generation.

### Steps to reproduce the problem

1. Select Controlnet Model and use Ending Control Step with a setting below 1, in this example 0.2
2. Generate Image
3. Generate again with same settings, now Ending Control Step is not working any more, result is like doing Ending Control Step with setting 1.0

### What should have happened?

Ending Control Step should have stopped at 0.2

### Commit where the problem happens

webui: version: [v1.9.0]  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2
controlnet: v1.1.443

### Command Line Arguments

```Shell
--xformers --force-enable-xformers --opt-split-attention --medvram --medvram-sdxl
```

### List of enabled extensions

![grafik](https://github.com/Mikubill/sd-webui-controlnet/assets/124619490/0a44be33-4ace-4d9b-befe-123bc0fb37e1)

### Console logs

```Shell
2024-04-16 00:10:59,718 - ControlNet - INFO - unit_separate = False, style_align = False 30/30 [00:13<00:00,  2.82it/s]
2024-04-16 00:10:59,719 - ControlNet - INFO - Loading model from cache: diffusers_xl_canny_small [e7fd4a83]
2024-04-16 00:10:59,721 - ControlNet - INFO - Using preprocessor: canny
2024-04-16 00:10:59,721 - ControlNet - INFO - preprocessor resolution = 512
2024-04-16 00:10:59,927 - ControlNet - INFO - ControlNet Hooked - Time = 0.2139420509338379
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.28it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.23it/s]
2024-04-16 00:11:29,486 - ControlNet - INFO - unit_separate = False, style_align = False 30/30 [00:13<00:00,  2.54it/s]
2024-04-16 00:11:29,486 - ControlNet - INFO - Loading model from cache: diffusers_xl_canny_small [e7fd4a83]
2024-04-16 00:11:29,487 - ControlNet - INFO - Using preprocessor: canny
2024-04-16 00:11:29,487 - ControlNet - INFO - preprocessor resolution = 512
2024-04-16 00:11:29,644 - ControlNet - INFO - ControlNet Hooked - Time = 0.16231560707092285
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.31it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.16it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.54it/s]
```

**Comment by travisg** [comment]
I've been debugging this a bit here, and it looks like something changed in stable diffusion webui that causes it to drop the guidance_schedule_handler callback after one run.

From what I can tell, [pull 2708](https://github.com/Mikubill/sd-webui-controlnet/pull/2708) actually papered over it, the real issue was the guidance_schedule_handler was getting callbacks after one run with what appears to be an 'old' self, with the control_params disabled.

It's a bit difficult to debug but it *seems* that the issue is in hook.py during restore() it tries to unregister the hook and clears out the control params, but the SD main app is still keeping it registered, and will continue to call back that one.

I bet it has something to do with https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0411eced89688f55aec356eea0c7d29377d37bc8 or https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/7e5e67330b092a65a8dd9e04a18969c458cb05d1

Somewhere in that logic where it's reordering the callbacks it seems to perhaps making a copy of the callback list and thus in the removal function it's not actually removing the old one, or even registering a new one, so it keeps calling back to the old instance.

**Comment by travisg** [comment]
I have a fix up on the main ui project.

**Comment by travisg** [comment]
It's not clear how to fix it locally in the controlnet repo without waiting for the fix to go in on the main UI. It seems like controlnet utilizes the hooks in a fairly unique way, at least among the extensions I have enabled here, where it registers and drops the guidance_schedule_handler every run, since its dynamically bound to the main object that is created each time.

**Comment by huchenlei** [comment]
> It's not clear how to fix it locally in the controlnet repo without waiting for the fix to go in on the main UI. It seems like controlnet utilizes the hooks in a fairly unique way, at least among the extensions I have enabled here, where it registers and drops the guidance_schedule_handler every run, since its dynamically bound to the main object that is created each time.

PR is welcomed. `hook.py` has many legacy hacks that can be improved.
