### ISSUE TITLE
why using img2img with controlnet result bad face?

### ISSUE THREAD

**Issue by jimys** [Mikubill/sd-webui-controlnet#436]
in img2img  using controlnet with openpose,  

result bad face, broken face,  

when disabled controlnet, everything will be fine

**Comment by brianebeling** [comment]
You should post some more information so that people can help you out.

Please include:
- a before and after
- The prompt and the information attached to that (you can find a copy pastable version below your result)
- The model and settings you used

I'm sure someone will be able to help you out with more information.

**Comment by jimys** [comment]
> You should post some more information so that people can help you out.
> 
> Please include:
> 
> * a before and after result
> * The prompt and the information attached to that (you can find a copy pastable version below your result)
> * The model and settings you used
> 
> I'm sure someone will be able to help you out with more information.

thank you, I thank the problem is become the img, I disable the img , now is much better

**Comment by OneLittleWolf** [comment]
@jimys I think you should be able to close this issue then.
