### ISSUE TITLE
Possible issue with API change PR

### ISSUE THREAD

**Issue by LonicaMewinsky** [Mikubill/sd-webui-controlnet#602]
WebUI: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
ControlNet: 8682c1e49728926bb7cc7753da8917d1ab095fb1

Following https://github.com/Mikubill/sd-webui-controlnet/pull/587, previously-working API implementation is now failing with
```
File "C:\sd2\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 181, in to_processing_unit
    assert isinstance(unit, ControlNetUnit), f'bad argument to controlnet extension: {unit}\nexpected Union[dict[str, Any], ControlNetUnit]'
```
Snippet of previously-working code:
```
cnet = importlib.import_module('extensions.sd-webui-controlnet.scripts.external_code', 'external_code')

...

            if cnet_present:
                cn_layers = cnet.get_all_units_in_processing(orig_p)
                new_layers = []
                for layer in cn_layers:
                    if (layer.image == None) and (layer.enabled == True):
                        nimg = np.array(image.convert("RGB"))
                        bimg = np.zeros((image.width, image.height, 3), dtype = np.uint8)
                        layer.image = {"image" : nimg, "mask" : bimg}
                    new_layers.append(layer)
                cnet.update_cn_script_in_processing(p, new_layers)
```

**Comment by ljleb** [comment]
Please provide an example request or the actual error message, not just the actual line of code where it happens as I am unable to reproduce otherwise.

**Comment by ljleb** [comment]
Looking into it.

**Comment by ljleb** [comment]
Seems to be caused by multiple classes `external_code.ControlNetUnit` being created (thanks @Vespinian for the investigation)

According to [this SO answer](https://stackoverflow.com/questions/46708659/isinstance-fails-for-a-type-imported-via-package-and-from-the-same-module-direct) this can occur when the same python module is accessible from multiple entries in `sys.path`. As we import the extension both from the extension itself and from other packages, we probably cannot even do a name check. It's generally a good idea to fail early.

I guess the assert is not really necessary, it was just a nice thing to have. Removed in https://github.com/Mikubill/sd-webui-controlnet/commit/426014e6335a9f4c088fb9426e8262d47375cda2.

**Comment by LonicaMewinsky** [comment]
Thanks a bunch. I want to be @ljleb when I grow up.
