### ISSUE TITLE
Scribble Mode (Reverse color) should be automatic

### ISSUE THREAD

**Issue by CCRcmcpe** [Mikubill/sd-webui-controlnet#7]
As the title described. If the user used open canvas and paint, inverse color should be automatically enabled to avoid bad generation quality and subsequent confusions.

Example:
![image](https://user-images.githubusercontent.com/40241855/218570983-1e5ab931-4638-4225-9409-b2f29e8f8e60.png)
^Enabled

![image](https://user-images.githubusercontent.com/40241855/218571065-85467063-0dc5-4ad0-8d32-8124b1b9f090.png)
^Disabled

**Comment by 2blackbar** [comment]
i agree, during importing  it should do negative filter

**Comment by younyokel** [comment]
Hey. I get white images no matter if I turn this on or off... What's the problem here?
![image](https://user-images.githubusercontent.com/53343081/219111050-992b2d63-7986-4440-87e3-f091c4d56d0b.png)
On.

![image](https://user-images.githubusercontent.com/53343081/219111163-68182955-20e6-4b32-a283-2fed0b80c51d.png)
Off.
